apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: k8s-mon-deployment
  name: k8s-mon-deployment
  namespace: kube-admin
data:
  k8s-mon.yml: |-
    kube_stats_metrics:
      user_specified: true
      addrs:
        - "http://kube-state-metrics.kube-system:8080/metrics"
      metrics_white_list:
      tags_white_list:
        - namespace
        - pod
        - pod_name
        - container
        - container_name
        - reason
        - secret
        - condition
        - node
        - deployment
        - configmap
        - daemonset
        - endpoint
        - replicaset
        - statefulset
        - persistentvolumeclaim
        - persistentvolume
        - service
        - phase
        - type
        - status
        - resource
        - unit
        - host_ip
        - pod_ip
        - cluster_ip
        - external_name
        - load_balancer_ip
        - storageclass
        - kernel_version
        - os_image
        - role
        - volume
        - access_mode
        - volumename
        - provisioner
        - reclaimPolicy
        - volumeBindingMode
        - poddisruptionbudget

    kube_etcd:
      concurrency_limit: 5
      user_specified: false
      addrs:
        - "https://localhost:2379/metrics"
      scheme: https
      metrics_path: metrics
      port: 2379
      tls_config:
        ca_file: /etc/secrets/etcd-certs/ca.crt
        cert_file: /etc/secrets/etcd-certs/healthcheck-client.crt
        key_file: /etc/secrets/etcd-certs/healthcheck-client.key
        insecure_skip_verify: true
      metrics_white_list:
        - go_gc_duration_seconds
        - go_goroutines
        - go_memstats_alloc_bytes
        - go_memstats_heap_inuse_bytes
        - go_memstats_stack_inuse_bytes
        - process_cpu_seconds_total
        - process_open_fds
        - process_resident_memory_bytes
        - etcd_debugging_mvcc_db_compaction_keys_total
        - etcd_debugging_mvcc_delete_total
        - etcd_debugging_mvcc_keys_total
        - etcd_debugging_mvcc_put_total
        - etcd_debugging_snap_save_total_duration_seconds
        - etcd_disk_backend_commit_duration_seconds
        - etcd_disk_wal_fsync_duration_seconds
        - etcd_mvcc_db_total_size_in_bytes
        - etcd_mvcc_db_total_size_in_use_in_bytes
        - etcd_network_client_grpc_received_bytes_total
        - etcd_network_client_grpc_sent_bytes_total
        - etcd_server_has_leader
        - etcd_server_health_failures
        - etcd_server_heartbeat_send_failures_total
        - etcd_server_id
        - etcd_server_is_leader
        - etcd_server_leader_changes_seen_total
        - etcd_server_proposals_applied_total
        - etcd_server_proposals_committed_total
        - etcd_server_proposals_failed_total
        - etcd_server_proposals_pending
        - etcd_server_quota_backend_bytes
        - etcd_server_slow_apply_total
        - etcd_server_slow_read_indexes_total
        - grpc_server_handled_total
        - grpc_server_started_total
      tags_white_list:

    apiserver:
      concurrency_limit: 5
      user_specified: false
      addrs:
        - "https://kubernetes.default/metrics"
      scheme: https
      metrics_path: metrics
      port: 6443
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      metrics_white_list:
        - go_gc_duration_seconds
        - go_goroutines
        - go_memstats_alloc_bytes
        - go_memstats_heap_inuse_bytes
        - go_memstats_stack_inuse_bytes
        - process_cpu_seconds_total
        - process_open_fds
        - process_resident_memory_bytes
        - rest_client_requests_total
        - rest_client_request_duration_seconds
        - apiserver_client_certificate_expiration_seconds
        - apiserver_current_inflight_requests
        - apiserver_current_inqueue_requests
        - apiserver_flowcontrol_current_executing_requests
        - apiserver_flowcontrol_current_inqueue_requests
        - apiserver_request_duration_seconds
        - apiserver_request_total
        - apiserver_response_sizes
        - apiserver_tls_handshake_errors_total
        - authentication_attempts
        - authentication_duration_seconds
        - etcd_db_total_size_in_bytes
        - etcd_object_counts
        - etcd_request_duration_seconds
        - workqueue_adds_total
        - workqueue_longest_running_processor_seconds
        - workqueue_queue_duration_seconds
        - workqueue_retries_total
        - workqueue_work_duration_seconds

    kube_scheduler:
      concurrency_limit: 5
      user_specified: false
      addrs:
        - "https://localhost:10259/metrics"
      scheme: https
      metrics_path: metrics
      port: 10259

      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      metrics_white_list:
        - go_gc_duration_seconds
        - go_goroutines
        - go_memstats_alloc_bytes
        - go_memstats_heap_inuse_bytes
        - go_memstats_stack_inuse_bytes
        - process_cpu_seconds_total
        - process_open_fds
        - process_resident_memory_bytes

        - rest_client_requests_total
        - rest_client_request_duration_seconds
        - workqueue_queue_duration_seconds
        - workqueue_work_duration_seconds
        - scheduler_e2e_scheduling_duration_seconds
        - scheduler_pod_scheduling_duration_seconds
        - scheduler_pending_pods
        - scheduler_queue_incoming_pods_total
        - scheduler_scheduling_algorithm_duration_seconds
        - scheduler_pod_scheduling_attempts
      tags_white_list:

    kube_controller_manager:
      concurrency_limit: 5
      user_specified: false
      addrs:
        - "https://localhost:10257/metrics"
      port: 10257
      scheme: https
      metrics_path: metrics
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      metrics_white_list:
        - go_gc_duration_seconds
        - go_goroutines
        - go_memstats_alloc_bytes
        - go_memstats_heap_inuse_bytes
        - go_memstats_stack_inuse_bytes
        - process_cpu_seconds_total
        - process_open_fds
        - process_resident_memory_bytes

        - workqueue_adds_total
        - workqueue_depth
        - rest_client_requests_total
        - rest_client_request_duration_seconds
        - workqueue_queue_duration_seconds
        - workqueue_work_duration_seconds

      tags_white_list:

    coredns:

      concurrency_limit: 5
      user_specified: false
      addrs:
        - "http://kube-dns.kube-system:9153/metrics"
      port: 9153
      scheme: http
      metrics_path: metrics
      metrics_white_list:
        - go_gc_duration_seconds
        - go_goroutines
        - go_memstats_alloc_bytes
        - go_memstats_heap_inuse_bytes
        - go_memstats_stack_inuse_bytes
        - process_cpu_seconds_total
        - process_open_fds
        - process_resident_memory_bytes
        - coredns_dns_requests_total
        - coredns_dns_responses_total
        - coredns_cache_entries
        - coredns_cache_hits_total
        - coredns_cache_misses_total
        - coredns_dns_request_duration_seconds
        - coredns_dns_response_size_bytes
      tags_white_list:

    kubelet_node:
      #hash_mod_num: 2
      #hash_mod_shard: 0
      concurrency_limit: 10
      user_specified: false
      addrs:
        - "https://127.0.0.1:10250/metrics"
      port: 10250
      scheme: https
      metrics_path: metrics
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      metrics_white_list:
        - kubelet_running_pods
        - kubelet_running_containers
        - volume_manager_total_volumes
        - kubelet_node_config_error
        - kubelet_runtime_operations_total
        - kubelet_runtime_operations_errors_total
        - kubelet_runtime_operations_duration_seconds
        - storage_operation_duration_seconds
        - kubelet_cgroup_manager_duration_seconds
        - rest_client_requests_total
        - rest_client_request_latency_seconds
      tags_white_list:

    kube_proxy:
      #hash_mod_num: 2
      #hash_mod_shard: 1
      concurrency_limit: 10
      user_specified: false
      addrs:
        - "http://127.0.0.1:10249/metrics"
      port: 10249
      scheme: http
      metrics_path: metrics
      metrics_white_list:
        - kubeproxy_sync_proxy_rules_duration_seconds
        - kubeproxy_network_programming_duration_seconds
        - rest_client_requests_total
        - rest_client_request_latency_seconds
      tags_white_list:

    append_tags:
    #      k1: v1
    #      k2: v2

    push_server_addr: "http://localhost:2080/api/collector/push"
    n9e_nid_label_name: "N9E_NID"
    multi_server_instance_unique_label: "server_addr"
    collect_step: 30 # 单位秒
    time_out_second: 5 # 单位秒
    server_side_nid: "6"
    collect_mode: "server_side"
    #   cadvisor_plugin 代表插件形式使用cadvisor raw api
    #   kubelet_agent   代表agent形式采集每个node的kubelet暴露的容器指标
    #   server_side     代表集中采集k8s服务组件共6个: apiserver、scheduler、controller-manager、etcd、coredns、kube-stats-metrics